feat: websocket plugin docs
emqx/neuron-docs pull request #211
Opened 2023-01-12 07:03 UTC by eeff

2023-01-29 02:26 UTC, lixiumei123 requested changes

2023-01-29 02:26 UTC, lixiumei123 commented on en_US/module-plugins/module-driver.md
> +### 应用配置
改成英文

2023-01-29 02:26 UTC, lixiumei123 commented on en_US/module-plugins/module-driver.md
> +| 字段                | 说明                                                         |
改成英文

2023-01-30 02:56 UTC, eeff commented on en_US/module-plugins/module-driver.md
> +### 应用配置
fix

2023-01-30 02:56 UTC, eeff commented on en_US/module-plugins/module-driver.md
> +| 字段                | 说明                                                         |
fix

2023-01-30 02:58 UTC, lixiumei123 approved these changes

2023-01-30 03:00 UTC, merged